# -*- coding: utf-8 -*-
"""MYMODULE.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OctiYkCfcSlhr6Ltk3pcxIqsm7xVpC-h
"""

list1=[]
for i in list1:
  print(i,end=" ")